version: 0.1

environment_variables:
  plaintext:
    key: "value"
            
phases:
  install:
    commands:
      - echo "Install started..."
#      - command
  pre_build:
    commands:
      - echo "Pre-build started..."
#      - command
  build:
    commands:
      - echo "build started..."
#      - command
  post_build:
    commands:
      - echo "post-build started..."
      - rm buildspec.yml
artifacts:
  files:
    - '**/*'
#  discard-paths: yes
